#ifndef AUDIO_H
#define AUDIO_H

#include <stdbool.h>
#include <SDL.h>

/*
 * Audio: square-wave tone (440 Hz) while sound_timer > 0. The tone is
 * generated by an SDL audio callback on its own thread; the emulator
 * thread only flips an atomic flag.
 */
typedef struct {
    bool initialized;
    SDL_AudioDeviceID device;
    SDL_atomic_t beeping;
    double phase; /* position inside the 440 Hz square wave (0..1) */
} Audio;

/* Opens the audio device. A missing device is not fatal: it only prints a
 * warning and leaves the emulator running silently. Returns false only on
 * a real failure. */
bool audio_init(Audio *audio);

/* Turns the tone on or off (called every frame with sound_timer > 0). */
void audio_set_beeping(Audio *audio, bool beeping);

/* Stops the callback and closes the device. */
void audio_close(Audio *audio);

#endif /* AUDIO_H */
